DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'guestportal_app') THEN
    CREATE ROLE guestportal_app LOGIN PASSWORD 'guestportal' NOSUPERUSER NOBYPASSRLS;
  END IF;
END
$$;

GRANT CONNECT ON DATABASE guestportal TO guestportal_app;
GRANT USAGE ON SCHEMA public TO guestportal_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO guestportal_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO guestportal_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO guestportal_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO guestportal_app;
